spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goal_achieve_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: DEBUG
    com.example.goal_achieve: DEBUG 