server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goalapp
    username: goalapp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

grpc:
  server:
    port: 6565
